import React,{useRef,useState} from 'react';
import './AdminPlazaCharacterV8.css';
import apiClient from '@/infra/api/apiClient';
export default function AdminPlazaCharacterV7({role,token}){
 const [hasError,setHasError]=useState(false);
 const [phone,setPhone]=useState(''),[data,setData]=useState(null),[character,setCharacter]=useState('girl'),[reason,setReason]=useState(''),[notice,setNotice]=useState(''),[busy,setBusy]=useState(false);const command=useRef(null);
 if(role!=='super_admin')return null;
 async function work(update){setBusy(true);setNotice('');setHasError(false);try{let result;if(update){const payload={phone,character,reason,expectedRevision:data.profile.revision};const key=JSON.stringify(payload);if(command.current?.key!==key)command.current={key,id:crypto.randomUUID()};result=await apiClient.put('/admin/plaza/character',{...payload,commandId:command.current.id},{headers:{Authorization:`Bearer ${token}`}});command.current=null;}else result=await apiClient.get('/admin/plaza/character',{params:{phone},headers:{Authorization:`Bearer ${token}`}});const next=result.data;setData(next);setCharacter(next.profile?.character||'girl');setNotice(update?'Đã cập nhật. Người chơi cần rời phòng rồi vào lại để nhận nhân vật mới.':'Đã lấy hồ sơ.');}catch(e){setHasError(true);const code=e.response?.data?.code;setNotice(({PLAZA_SUPER_ADMIN_REQUIRED:'Phiên Super Admin chưa hợp lệ. Hãy đăng nhập lại.',PLAZA_CUSTOMER_NOT_FOUND:'Không tìm thấy duy nhất một tài khoản với số điện thoại này.',PLAZA_PROFILE_CONFLICT:'Hồ sơ vừa thay đổi. Bấm Tìm người chơi để lấy lại hồ sơ.',PLAZA_INVALID_REQUEST:'Hãy chọn nhân vật và nhập lý do từ 5 đến 500 ký tự.',PLAZA_PROFILE_UNAVAILABLE:'Chưa truy cập được hồ sơ. Hãy thử lại.'})[code]||'Chưa nhận được xác nhận. Hãy thử lại cùng yêu cầu; hệ thống sẽ chống lưu trùng.');}finally{setBusy(false);}}
 return <section className="plaza-admin-v8"><h3>Nhân vật Cing Plaza</h3><p>Quản lý giới tính nhân vật · Dành cho Super Admin</p><div className="plaza-admin-v8__lookup"><label>Số điện thoại người chơi<input inputMode="tel" aria-label="Số điện thoại" value={phone} onChange={e=>{setPhone(e.target.value);setData(null);setNotice('');command.current=null;}} placeholder="0xxxxxxxxx"/></label><button disabled={busy||!token||!/^0[0-9]{9}$/.test(phone)} onClick={()=>work(false)}>{busy?'Đang xử lý…':'Tìm người chơi'}</button></div>{data&&<div><p><strong>{data.customer?.name||data.customer?.phone}</strong> · Nhân vật hiện tại: {data.profile?.character==='boy'?'Nam':data.profile?.character==='girl'?'Nữ':'Chưa chọn'}</p>{data.profile?<div className="plaza-admin-v8__edit"><label>Giới tính mới<select aria-label="Nhân vật mới" value={character} onChange={e=>setCharacter(e.target.value)}><option value="boy">Nam</option><option value="girl">Nữ</option></select></label><label>Lý do thay đổi<input aria-label="Lý do thay đổi" aria-describedby="plaza-admin-reason-hint" value={reason} onChange={e=>setReason(e.target.value)} placeholder="Ví dụ: Đổi theo yêu cầu người chơi" maxLength={500}/><small id="plaza-admin-reason-hint">Ít nhất 5 ký tự · Đã nhập {reason.trim().length}/500</small></label><button disabled={busy||reason.trim().length<5||character===data.profile.character} onClick={()=>work(true)}>Lưu thay đổi nhân vật</button></div>:<p>Người chơi cần chọn nhân vật lần đầu trong Cing Plaza.</p>}</div>}{notice&&<p role={hasError?'alert':'status'} className="plaza-admin-v8__notice" data-error={hasError}>{notice}</p>}</section>;
}
