export const DASHBOARD_REALTIME_CONFIG = {

  ACTIVITY_FEED_LIMIT: 30,

  LEADERBOARD_LIMIT: 10,

  REVENUE_PULSE_INTERVAL: 3000,

  ORDER_TRACKER_BATCH_SIZE: 20,

  CUSTOMER_PRESENCE_TIMEOUT: 60000,

  LIVE_WIDGET_REFRESH_MS: 5000,

  MAX_REALTIME_QUEUE: 100,

};