import test from 'node:test';import assert from 'node:assert/strict';
import {createPlazaChessAudioV4,PLAZA_CHESS_SOUND_FILES,plazaChessAudioCuesV4} from '../scene/plazaChessAudioV4.js';
function setup({failed=null}={}){const calls={contexts:0,resumes:0,closed:0,urls:[],started:0,stopped:0,volumes:[]};let hidden=false;
 class Context{constructor(){calls.contexts++;this.state='suspended';this.destination={};}resume(){calls.resumes++;this.state='running';return Promise.resolve();}suspend(){this.state='suspended';return Promise.resolve();}close(){calls.closed++;this.state='closed';return Promise.resolve();}decodeAudioData(bytes){return Promise.resolve({bytes});}createBufferSource(){return{connect(){},disconnect(){},start(){calls.started++;},stop(){calls.stopped++;this.onended?.();}};}createGain(){const gain={gain:{value:0},connect(){calls.volumes.push(this.gain.value);},disconnect(){}};return gain;}}
 const runtime=createPlazaChessAudioV4({AudioContextClass:Context,fetcher:async url=>{calls.urls.push(url);return {ok:url!==failed,arrayBuffer:async()=>new ArrayBuffer(4)};},isHidden:()=>hidden});return{runtime,calls,hide:value=>hidden=value};}
test('same four Chess paths, .65 volume; no context/fetch until a user gesture',async()=>{const s=setup();assert.equal(s.calls.contexts,0);assert.equal(s.calls.urls.length,0);assert.equal(s.runtime.play('move'),false);assert.equal(await s.runtime.unlockFromGesture(),true);assert.equal(s.calls.contexts,1);assert.deepEqual(s.calls.urls,Object.values(PLAZA_CHESS_SOUND_FILES));assert.equal(s.runtime.play('capture'),true);assert.equal(s.calls.started,1);assert.equal(s.calls.volumes[0],.65);await s.runtime.unlockFromGesture();assert.equal(s.calls.contexts,1);assert.equal(s.calls.urls.length,4);s.runtime.dispose();});
test('failed buffer does not block other cues, retries only missing file',async()=>{const s=setup({failed:PLAZA_CHESS_SOUND_FILES.warning});assert.equal(await s.runtime.unlockFromGesture(),false);assert.equal(s.runtime.play('move'),true);assert.equal(s.runtime.play('warning'),false);await s.runtime.unlockFromGesture();assert.equal(s.calls.urls.length,5);assert.equal(s.calls.urls.at(-1),PLAZA_CHESS_SOUND_FILES.warning);s.runtime.dispose();});
test('hide stops sources and suppresses cues; resume reuses context, dispose is final',async()=>{const s=setup();await s.runtime.unlockFromGesture();s.runtime.play('check');s.hide(true);s.runtime.suspend();assert.equal(s.calls.stopped,1);assert.equal(s.runtime.play('check'),false);s.runtime.resumeExisting();s.hide(false);s.runtime.resumeExisting();assert.equal(s.runtime.play('check'),true);s.runtime.dispose();assert.equal(s.calls.closed,1);assert.equal(s.runtime.play('check'),false);assert.equal(await s.runtime.unlockFromGesture(),false);s.runtime.dispose();assert.equal(s.calls.closed,1);});
test('unsupported browser audio never interrupts game',async()=>{const s=createPlazaChessAudioV4({AudioContextClass:null});assert.equal(await s.unlockFromGesture(),false);assert.equal(s.play('move'),false);s.suspend();s.resumeExisting();s.dispose();});
const state=(extra={})=>({matchId:'m',phase:'active',ply:0,fen:'board w',players:[{memberId:'a',color:'w'},{memberId:'b',color:'b'}],lastMove:null,...extra});
test('no replay on initial snapshot, another match, repeated revision or rewind',()=>{const s=state({ply:10,lastMove:{san:'Qxh7+'}});for(const old of [null,s,state({matchId:'other'}),state({ply:11})])assert.deepEqual(plazaChessAudioCuesV4(old,s,'a'),[]);});
test('check > capture; watcher hears check/capture without a misleading your-turn cue',()=>{assert.deepEqual(plazaChessAudioCuesV4(state(),state({ply:1,lastMove:{san:'Qxh7+'}}),'watcher'),['check']);assert.deepEqual(plazaChessAudioCuesV4(state(),state({ply:1,lastMove:{san:'exd6'}}),'watcher'),['capture']);assert.deepEqual(plazaChessAudioCuesV4(state(),state({ply:1,fen:'board b',lastMove:{san:'e4'}}),'watcher'),[]);});
test('your-turn sound follows authoritative turn/start, never local optimistic click',()=>{assert.deepEqual(plazaChessAudioCuesV4(state({phase:'preparing'}),state(),'a'),['move']);assert.deepEqual(plazaChessAudioCuesV4(state(),state({ply:1,fen:'board b',lastMove:{san:'e4'}}),'b'),['move']);assert.deepEqual(plazaChessAudioCuesV4(state(),state({ply:1,fen:'board b',lastMove:{san:'e4'}}),'a'),[]);assert.deepEqual(plazaChessAudioCuesV4(state({fen:'board b'}),state({ply:1,phase:'finished',lastMove:{san:'Qh4#'}}),'b'),['check']);});
