import test from 'node:test';import assert from 'node:assert/strict';import{readFile}from'node:fs/promises';import*as T from'three';import{GLTFLoader}from'three/addons/loaders/GLTFLoader.js';import{VRMLoaderPlugin}from'@pixiv/three-vrm';import{VRMAnimationLoaderPlugin,createVRMAnimationClip}from'@pixiv/three-vrm-animation';
const l=new GLTFLoader();l.register(p=>new VRMLoaderPlugin(p));l.register(p=>new VRMAnimationLoaderPlugin(p));l.register(()=>({name:'V15_TEXTURE_STUB',loadTexture:()=>Promise.resolve(new T.Texture())}));async function load(n){const b=await readFile(new URL('../../../../public/cing-plaza/assets/'+n,import.meta.url));return l.parseAsync(b.buffer.slice(b.byteOffset,b.byteOffset+b.byteLength),'');}
for(const character of ['boy','girl'])test(`${character}: planted foot matches full and half travel speeds, arms oppose the stride, fingers stay relaxed`,async()=>{const v=(await load(`cing-${character}-v01.vrm`)).userData.vrm,c=createVRMAnimationClip((await load(`cing-${character}-walk.vrma`)).userData.vrmAnimations[0],v),m=new T.AnimationMixer(v.scene),a=m.clipAction(c).play();a.setLoop(T.LoopOnce,1);a.clampWhenFinished=true;
 const point=n=>v.humanoid.getNormalizedBoneNode(n).getWorldPosition(new T.Vector3());
 for(const speed of [1.35,.675,.3375]){let fixed;for(let elapsed=0;elapsed<=.16;elapsed+=.02){const localTime=.08+elapsed*speed/1.35;m.setTime(localTime);v.update(0);v.scene.updateMatrixWorld(true);const planted=point('leftFoot').z+speed*elapsed;if(fixed===undefined)fixed=planted;assert.ok(Math.abs(planted-fixed)<.002,'supporting foot slides in world space');}}
 const poses=[];for(const t of [0,c.duration/2]){m.setTime(t);v.update(0);v.scene.updateMatrixWorld(true);poses.push({hand:point('leftHand').z,foot:point('leftFoot').z});}assert.ok((poses[0].hand-poses[1].hand)*(poses[0].foot-poses[1].foot)<0,'arm swings with same-side leg');assert.ok(Math.abs(poses[0].hand-poses[1].hand)>.20,'arm swing too small');
 for(const name of ['idle','walk']){a.stop();const clip=createVRMAnimationClip((await load(`cing-${character}-${name}.vrma`)).userData.vrmAnimations[0],v),action=m.clipAction(clip).play();m.setTime(.12);v.update(0);for(const[side,sign]of [['left',-1],['right',1]]){let previous=0;for(const f of ['Index','Middle','Ring','Little']){const q=v.humanoid.getNormalizedBoneNode(side+f+'Proximal').quaternion,angle=2*Math.asin(sign*q.z);assert.ok(angle>previous&&angle<.7,'finger curl must gradually increase toward little finger');previous=angle;}assert.ok(v.humanoid.getNormalizedBoneNode(side+'ThumbProximal').quaternion.angleTo(new T.Quaternion())>.1,'thumb remains rigid');}action.stop();}
 m.uncacheRoot(v.scene);
});
