import test from'node:test';import assert from'node:assert/strict';import{readFile}from'node:fs/promises';import*as T from'three';import{GLTFLoader}from'three/addons/loaders/GLTFLoader.js';import{buildWorldV3}from'../scene/plazaWorldV3.js';
async function build(){const b=await readFile(new URL('../../../../public/cing-plaza/assets/cing-plaza-map-v17.glb',import.meta.url)),l=new GLTFLoader();l.register(()=>({name:'HERITAGE_V13_TEST',loadTexture:()=>Promise.resolve(new T.Texture())}));const map=(await l.parseAsync(b.buffer.slice(b.byteOffset,b.byteOffset+b.byteLength),'')).scene;return{map,w:buildWorldV3(map,{labelFactory:()=>new T.MeshBasicMaterial()})};}
test('all sixty timber columns meet longitudinal ties and supported transverse rafters with joined roof ridge layers',async()=>{
 const{map,w}=await build(),h=w.heritageV13,d=w.dinhV12;assert.equal(h.ties.length,16);assert.equal(h.rafters.length,70);assert.equal(h.rims.length,15);
 for(const column of d.columns){const[,i,j]=column.name.match(/_(\d+)_(\d+)$/),box=new T.Box3().setFromObject(column),head=map.getObjectByName(`V13_Column_Head_${i}_${j}`);assert.ok(head&&box.intersectsBox(new T.Box3().setFromObject(head)));const tie=h.ties.find(o=>o.name===`V13_Longitudinal_Tie_${j}`);assert.ok(box.intersectsBox(new T.Box3().setFromObject(tie)));const rafters=h.rafters.filter(o=>o.name.startsWith(`V13_Transverse_Rafter_${i}_`));assert.ok(rafters.some(o=>new T.Box3().setFromObject(o).distanceToPoint(head.position)<.2));}
 for(const o of h.rims){const p=o.geometry.attributes.position;assert.ok([...p.array].every(Number.isFinite));assert.ok(new T.Box3().setFromObject(o).getSize(new T.Vector3()).length()>4);}
});
test('five forecourt planters removed with plants; bronze censer centred before entrance with three legs and two handles',async()=>{
 const{map,w}=await build(),h=w.heritageV13;assert.equal(h.cleared.beds.length,5);assert.ok(h.cleared.removedTriangles>100);for(const n of ['V15_Garden_Planter_Dark_Soil010','V15_Garden_Planter_Dark_Soil011','V15_Garden_Planter_Dark_Soil012','V17_Garden_Planter_Soil004','V17_Garden_Planter_Soil005'])assert.equal(map.getObjectByName(n),undefined);
 assert.equal(h.urn.position.x,14.5);assert.ok(h.urn.position.z>-20.3&&h.urn.position.z<-15);assert.equal(h.urn.children.filter(o=>o.name.startsWith('V13_Censer_Leg_')).length,3);assert.equal(h.urn.children.filter(o=>o.name.startsWith('V13_Censer_Scroll_Handle_')).length,2);assert.ok(map.getObjectByName('V13_Censer_Hollow_Bronze_Bowl').material.metalness>.8);assert.ok(w.obstacles.includes(h.obstacle));assert.ok(h.obstacle.minX>13.7&&h.obstacle.maxX<15.3);
 const plants=[];map.traverse(o=>{if(o.isMesh&&/Garden_Individual_Folded_Foliage_|Hundreds_Of_Ivory_Flowers_|Flower_Stems|Garden_New_(?:Foliage|Flowers)_/.test(o.name))plants.push(o);});for(const o of plants){const a=o.geometry.attributes.position;for(let i=0;i<a.count;i+=3){const c=new T.Vector3();for(let j=0;j<3;j++)c.add(new T.Vector3().fromBufferAttribute(a,i+j).applyMatrix4(o.matrixWorld).divideScalar(3));assert.ok(!h.cleared.beds.some(b=>c.x>=b.min.x-.24&&c.x<=b.max.x+.24&&c.z>=b.min.z-.24&&c.z<=b.max.z+.24),'orphan plant in cleared court');}}
});
