const DATABASE='cing-plaza-photos-v11',STORE='photos';
function open(){return new Promise((resolve,reject)=>{if(!globalThis.indexedDB)return reject(new Error('PHOTO_STORAGE_UNAVAILABLE'));const req=indexedDB.open(DATABASE,1);req.onupgradeneeded=()=>req.result.createObjectStore(STORE,{keyPath:'id'}).createIndex('ownerId','ownerId');req.onsuccess=()=>resolve(req.result);req.onerror=()=>reject(req.error);req.onblocked=()=>reject(new Error('PHOTO_STORAGE_BUSY'));});}
async function transaction(mode,work){const db=await open();try{return await new Promise((resolve,reject)=>{const tx=db.transaction(STORE,mode);let result;tx.oncomplete=()=>resolve(result);tx.onerror=()=>reject(tx.error);tx.onabort=()=>reject(tx.error||new Error('PHOTO_STORAGE_FAILED'));work(tx.objectStore(STORE),value=>result=value);});}finally{db.close();}}
function owner(value){if(typeof value!=='string'||!value)throw new Error('PHOTO_ACCOUNT_REQUIRED');return value;}
export async function savePlazaPhotoV11(ownerId,blob){owner(ownerId);if(!(blob instanceof Blob)||!blob.size)throw new Error('PHOTO_EMPTY');const item={id:crypto.randomUUID(),ownerId,createdAt:Date.now(),blob};await transaction('readwrite',(store,set)=>{const req=store.index('ownerId').getAll(ownerId);req.onsuccess=()=>{const old=req.result.sort((a,b)=>a.createdAt-b.createdAt);if(old.length>=60){store.transaction.abort();return;}store.add(item);set(item);};});return item;}
export async function listPlazaPhotosV11(ownerId){owner(ownerId);return transaction('readonly',(store,set)=>{const req=store.index('ownerId').getAll(ownerId);req.onsuccess=()=>set(req.result.sort((a,b)=>b.createdAt-a.createdAt));});}
export async function deletePlazaPhotoV11(ownerId,id){owner(ownerId);return transaction('readwrite',(store,set)=>{const req=store.get(id);req.onsuccess=()=>{if(req.result?.ownerId===ownerId)store.delete(id);set(true);};});}
export function downloadPlazaPhotoV11(photo){const url=URL.createObjectURL(photo.blob),link=document.createElement('a');link.href=url;link.download='cing-plaza-'+photo.createdAt+'.png';link.click();setTimeout(()=>URL.revokeObjectURL(url),30000);}
export function sharePlazaPhotoV11(photo){const file=new File([photo.blob],'cing-plaza.png',{type:'image/png'});if(navigator.canShare?.({files:[file]}))return navigator.share({files:[file],title:'Cing Plaza'});downloadPlazaPhotoV11(photo);return Promise.resolve();}
