import PlazaInventoryV16 from './PlazaInventoryV16.jsx';
import {findRoomNumberV15, validRoomNameV15, roomNameV15} from './plazaSocialV15.js';
import './PlazaSocialV15.css';
import PlazaLoadingV11 from './PlazaLoadingV11.jsx';
import React,{useState,useEffect} from 'react';
import {injectTierBadgeStyles} from '../../../membership/components/TierBadgeStyles.js';
import PlazaTitleV10 from './PlazaTitleV10.jsx';
import './PlazaIdentityV9.css';
import {DoorOpen,ShoppingBag,Shirt,Lock,Plus,ChevronLeft,RefreshCw,MessageCircle,ArrowUpRight} from 'lucide-react';
export default function PlazaLobbyV7({identity,onChooseBadge,profile,connected,busy,rooms,choose,onCreate,onJoin,onRefresh,onClose,onChat,onLookupRooms,social,onProfile}){
 useEffect(()=>{injectTierBadgeStyles();},[]);
 const [view,setView]=useState('hub'),[password,setPassword]=useState(''),[locked,setLocked]=useState(false),[modal,setModal]=useState(null),[roomName,setRoomName]=useState('');
 const [search,setSearch]=useState(''),[searchError,setSearchError]=useState(''),[searchBusy,setSearchBusy]=useState(false),[formError,setFormError]=useState('');
 async function findRoom(e){e.preventDefault();if(searchBusy||busy||!connected)return;setSearchError('');setSearchBusy(true);try{const data=onLookupRooms?await onLookupRooms():{rooms};const result=findRoomNumberV15(data.rooms||[],search);if(result.error)setSearchError(result.error);else if(result.room.hasPassword){setModal(result.room);setPassword('');setFormError('');}else await onJoin(result.room.roomId);}catch{setSearchError('Chưa tìm được phòng. Hãy thử lại.');}finally{setSearchBusy(false);}}
 const portraits=key=>`/cing-plaza/assets/v7/${key}-portrait.webp`;
 const title={hub:'Cing Plaza',rooms:'Phòng trò chuyện',wardrobe:'Tủ đồ của bạn',shop:'Siêu thị Cing'};
 return <div className={"plaza-v7-lobby "+(["wardrobe","shop"].includes(view)?"plaza-v16-inventory-lobby":"")}><header><button aria-label="Quay lại" onClick={()=>view==='hub'?onClose?.():setView('hub')}><ChevronLeft/></button><strong>{title[view]}</strong><button aria-label="Mở trò chuyện" onClick={onChat}><MessageCircle/></button></header>
 {profile===undefined?<div className="plaza-v7-loading"><PlazaLoadingV11/><button disabled={!connected||busy} onClick={onRefresh}>Thử lại</button></div>:profile===null?<section className="plaza-v7-choice"><p className="plaza-v7-kicker">BẮT ĐẦU CÂU CHUYỆN CỦA BẠN</p><h1>Chọn nhân vật của bạn</h1><p>Giới tính nhân vật sẽ đi theo tài khoản của bạn.</p><div>{['boy','girl'].map(key=><button key={key} disabled={!connected||busy} onClick={()=>choose(key)}><img src={portraits(key)} alt={key==='boy'?'Nhân vật nam mặc định':'Nhân vật nữ mặc định'}/><span>{key==='boy'?'Nhân vật nam':'Nhân vật nữ'}</span></button>)}</div></section>:<>
 {view==='hub'?<><section className="plaza-v7-hero"><p className="plaza-v7-kicker">MỘT KHÔNG GIAN · NHIỀU CUỘC GẶP</p><h1>Cing<br/>Plaza<span>✦</span></h1><p>Gặp gỡ, tương tác, pk game<br/>và cùng nhau trò chuyện</p><img src={portraits(profile.character)} alt="Nhân vật của bạn"/></section><button className="plaza-v16-hub-profile" onClick={onProfile}>Hồ sơ Cing Plaza · Bạn bè & PM</button><nav className="plaza-v7-destinations">{[['wardrobe',Shirt,'Tủ đồ','Phong cách của bạn'],['shop',ShoppingBag,'Siêu thị','Khám phá điều mới'],['rooms',DoorOpen,'Phòng trò chuyện','Gặp nhau tại Plaza']].map(([id,Icon,label,sub])=><button key={id} onClick={()=>setView(id)}><Icon/><span><strong>{label}</strong><small>{sub}</small></span><ArrowUpRight/></button>)}</nav><p className="plaza-v7-footer">{rooms.length} phòng đang có người · tối đa 30 người / phòng</p></>:view==='rooms'?<section className="plaza-v7-directory"><div className="plaza-v7-section"><h1>Hẹn nhau tại Plaza</h1><p>Chọn một cuộc gặp, hoặc mở phòng của riêng bạn.</p><div><button disabled={!connected||busy} onClick={()=>{setModal({create:true});setPassword('');setRoomName('');setLocked(false);setFormError('');}}><Plus/> Tạo phòng mới</button><button aria-label="Cập nhật phòng" disabled={!connected||busy} onClick={onRefresh}><RefreshCw/></button></div></div><form className="plaza-v15-room-search" onSubmit={findRoom}><label htmlFor="plaza-room-number">Tìm phòng theo số</label><div><input id="plaza-room-number" inputMode="numeric" pattern="[0-9]*" maxLength={12} value={search} onChange={e=>{setSearch(e.target.value);setSearchError('');}} placeholder="Ví dụ: 02"/><button disabled={!connected||busy||searchBusy||!search.trim()}>Vào phòng</button></div>{searchError&&<p role="alert">{searchError}</p>}</form><div className="plaza-v7-rooms">{rooms.filter(r=>r.memberCount>0).map((r,i)=><button key={r.roomId} className="plaza-v7-room" disabled={!connected||busy||r.memberCount>=r.capacity} onClick={()=>r.hasPassword?(setModal(r),setPassword(''),setFormError('')):onJoin(r.roomId)}><span className="plaza-v7-room-number">{String(r.roomNumber||i+1).padStart(2,'0')}</span><span><strong>{r.name} {r.hasPassword&&<Lock size={14} aria-label="Có mật khẩu"/>}</strong><small>Cing Plaza {String(r.roomNumber||i+1).padStart(2,'0')} · {r.memberCount}/{r.capacity} người</small></span><b>{r.memberCount>=r.capacity?'FULL':'Vào phòng →'}</b></button>)}{rooms.length===0&&<div className="plaza-v7-empty"><DoorOpen/><h2>Cuộc gặp đầu tiên chờ bạn</h2><p>Tạo phòng để mời bạn bè vào Plaza.</p></div>}</div></section>:<PlazaInventoryV16 mode={view} identity={identity} character={profile.character} social={social} onChooseBadge={onChooseBadge} onProfile={onProfile}/>}</>}
 {modal&&<div className="plaza-v7-modal"><form onSubmit={async e=>{e.preventDefault();setFormError('');if(modal.create&&!validRoomNameV15(roomName)){setFormError('Tên phòng cần từ 1 đến 30 ký tự.');return;}const ok=modal.create?await onCreate(roomNameV15(roomName),locked?password:''):await onJoin(modal.roomId,password);if(ok){setModal(null);setPassword('');}}}><h2>{modal.create?'Tạo phòng mới':modal.name}</h2>{modal.create&&<label>Tên phòng<input autoFocus type="text" value={roomName} onChange={e=>setRoomName([...e.target.value.normalize('NFC')].slice(0,30).join(''))} minLength={1} maxLength={60} required placeholder="Đặt tên cho cuộc gặp của bạn"/><small>{[...roomNameV15(roomName)].length}/30 ký tự</small></label>}{modal.create&&<label><input type="checkbox" checked={locked} onChange={e=>setLocked(e.target.checked)}/> Đặt mật khẩu</label>}{(!modal.create||locked)&&<label>Mật khẩu<input autoFocus type="password" value={password} onChange={e=>setPassword(e.target.value)} minLength={4} maxLength={64} required/></label>}{formError&&<p role="alert">{formError}</p>}<p>Tối đa 30 người mỗi phòng.</p><button disabled={!connected||busy||(modal.create&&!validRoomNameV15(roomName))}> {modal.create?'Tạo phòng':'Vào phòng'} </button><button type="button" disabled={busy} onClick={()=>setModal(null)}>Hủy</button></form></div>}
 </div>;
}
