import PlazaTitleV10 from './PlazaTitleV10.jsx';
import {selectPlazaRoomChatV8} from './plazaChatScopeV8.js';
import React,{useEffect,useRef,useState} from 'react';
import {X,Send,MessagesSquare,Globe,Mail,MessageCircle} from 'lucide-react';
const channels=[['room','Khu vực',MessageCircle],['world','Loa thế giới',Globe],['pm','PM',Mail],['all','Tất cả',MessagesSquare]];
export default function PlazaChatV7({room,messages,draft,setDraft,submit,connected,busy,onClose}){
 const visibleMessages=selectPlazaRoomChatV8(room,messages);
 const [tab,setTab]=useState('room'),ref=useRef(null),end=useRef(null);const active=tab==='room'||tab==='all';const closeRef=useRef(onClose);closeRef.current=onClose;
 useEffect(()=>{const previous=document.activeElement;ref.current?.querySelector('button')?.focus({preventScroll:true});function keys(e){if(e.key==='Escape')closeRef.current();if(e.key==='Tab'){const items=[...ref.current.querySelectorAll('button:not(:disabled),textarea:not(:disabled)')];if(!items.length)return;const first=items[0],last=items.at(-1);if(e.shiftKey&&document.activeElement===first){e.preventDefault();last.focus();}else if(!e.shiftKey&&document.activeElement===last){e.preventDefault();first.focus();}}}document.addEventListener('keydown',keys);return()=>{document.removeEventListener('keydown',keys);previous?.focus?.({preventScroll:true});};},[]);
 useEffect(()=>end.current?.scrollIntoView({block:'nearest'}),[visibleMessages.at(-1)?.messageId,tab]);
 return <section ref={ref} className="plaza-v7-chat" role="dialog" aria-modal="true" aria-label="Trò chuyện Cing Plaza"><header><div><small>TRÒ CHUYỆN</small><h2>{room?.name||'Sảnh Cing Plaza'}</h2></div><button aria-label="Đóng trò chuyện" onClick={onClose}><X/></button></header><div className="plaza-v7-tabs" role="tablist" aria-label="Kênh trò chuyện">{channels.map(([id,label,Icon],i)=><button key={id} id={'chat-tab-'+id} aria-controls="chat-channel" role="tab" aria-selected={tab===id} tabIndex={tab===id?0:-1} onKeyDown={e=>{if(['ArrowLeft','ArrowRight','Home','End'].includes(e.key)){e.preventDefault();const next=e.key==='Home'?0:e.key==='End'?3:(i+(e.key==='ArrowRight'?1:3))%4;setTab(channels[next][0]);document.getElementById('chat-tab-'+channels[next][0])?.focus();}}} onClick={()=>setTab(id)}><Icon size={17}/><span>{label}</span></button>)}</div><div id="chat-channel" className="plaza-v7-chat-stream" role="tabpanel" aria-labelledby={'chat-tab-'+tab}>{!active?<div className="plaza-v7-chat-empty"><h3>{tab==='pm'?'Tin nhắn riêng':'Loa thế giới'}</h3><p>{tab==='pm'?'Kênh riêng cho hai người sẽ mở cùng hệ thống bạn bè.':'Kênh toàn server sẽ mở khi có vật phẩm loa.'}</p><small>Tính năng đang được chuẩn bị</small></div>:!room?<div className="plaza-v7-chat-empty">Chat khu vực chỉ hiển thị trong phòng bạn đang đứng. Loa thế giới và PM sẽ được bổ sung sau.</div>:<>{visibleMessages.length===0&&<div className="plaza-v7-chat-empty">Bắt đầu bằng một lời chào nhé.</div>}{visibleMessages.map(m=><article key={m.messageId}><div><strong>{m.author?.displayName||'Cing iu'}</strong>{m.author?.selectedBadge&&<PlazaTitleV10 titleKey={m.author.selectedBadge} size="chat"/>}<time>{new Date(m.createdAt).toLocaleTimeString('vi-VN',{hour:'2-digit',minute:'2-digit'})}</time></div><p>{m.body}</p></article>)}<div ref={end}/></>}</div><form onSubmit={submit}><textarea aria-label="Tin nhắn" placeholder={active&&room?'Nhắn một lời với Cing iu…':'Kênh chưa thể gửi tin nhắn'} rows={1} maxLength={500} value={draft} disabled={!active||!room||!connected} onChange={e=>setDraft(e.target.value)}/><button aria-label="Gửi tin nhắn" disabled={!active||!room||!connected||busy||!draft.trim()}><Send size={21}/></button></form></section>;
}
