import React,{useState} from 'react';
import {DoorOpen,ShoppingBag,Shirt,Lock,Plus,ChevronLeft,RefreshCw,MessageCircle,ArrowUpRight} from 'lucide-react';
export default function PlazaLobbyV7({profile,connected,busy,rooms,choose,onCreate,onJoin,onRefresh,onClose,onChat}){
 const [view,setView]=useState('hub'),[password,setPassword]=useState(''),[locked,setLocked]=useState(false),[modal,setModal]=useState(null);
 const portraits=key=>`/cing-plaza/assets/v7/${key}-portrait.webp`;
 const title={hub:'Cing Plaza',rooms:'Phòng trò chuyện',wardrobe:'Tủ đồ của bạn',shop:'Siêu thị Cing'};
 return <div className="plaza-v7-lobby"><header><button aria-label="Quay lại" onClick={()=>view==='hub'?onClose?.():setView('hub')}><ChevronLeft/></button><strong>{title[view]}</strong><button aria-label="Mở trò chuyện" onClick={onChat}><MessageCircle/></button></header>
 {profile===undefined?<div className="plaza-v7-loading">{connected?'Đang lấy hồ sơ nhân vật…':'Đang kết nối Plaza…'}<button disabled={!connected||busy} onClick={onRefresh}>Thử lại</button></div>:profile===null?<section className="plaza-v7-choice"><p className="plaza-v7-kicker">BẮT ĐẦU CÂU CHUYỆN CỦA BẠN</p><h1>Chọn nhân vật của bạn</h1><p>Giới tính nhân vật sẽ đi theo tài khoản của bạn.</p><div>{['boy','girl'].map(key=><button key={key} disabled={!connected||busy} onClick={()=>choose(key)}><img src={portraits(key)} alt={key==='boy'?'Nhân vật nam mặc định':'Nhân vật nữ mặc định'}/><span>{key==='boy'?'Nhân vật nam':'Nhân vật nữ'}</span></button>)}</div></section>:<>
 {view==='hub'?<><section className="plaza-v7-hero"><p className="plaza-v7-kicker">MỘT KHÔNG GIAN · NHIỀU CUỘC GẶP</p><h1>Cing<br/>Plaza<span>✦</span></h1><p>Gặp gỡ, tương tác, pk game<br/>và cùng nhau trò chuyện</p><img src={portraits(profile.character)} alt="Nhân vật của bạn"/></section><nav className="plaza-v7-destinations">{[['wardrobe',Shirt,'Tủ đồ','Phong cách của bạn'],['shop',ShoppingBag,'Siêu thị','Khám phá điều mới'],['rooms',DoorOpen,'Phòng trò chuyện','Gặp nhau tại Plaza']].map(([id,Icon,label,sub])=><button key={id} onClick={()=>setView(id)}><Icon/><span><strong>{label}</strong><small>{sub}</small></span><ArrowUpRight/></button>)}</nav><p className="plaza-v7-footer">{rooms.length} phòng đang có người · tối đa 30 người / phòng</p></>:view==='rooms'?<section className="plaza-v7-directory"><div className="plaza-v7-section"><h1>Hẹn nhau tại Plaza</h1><p>Chọn một cuộc gặp, hoặc mở phòng của riêng bạn.</p><div><button disabled={!connected||busy} onClick={()=>{setModal({create:true});setPassword('');setLocked(false);}}><Plus/> Tạo phòng mới</button><button aria-label="Cập nhật phòng" disabled={!connected||busy} onClick={onRefresh}><RefreshCw/></button></div></div><div className="plaza-v7-rooms">{rooms.filter(r=>r.memberCount>0).map((r,i)=><button key={r.roomId} className="plaza-v7-room" disabled={!connected||busy||r.memberCount>=r.capacity} onClick={()=>r.hasPassword?(setModal(r),setPassword('')):onJoin(r.roomId)}><span className="plaza-v7-room-number">{String(i+1).padStart(2,'0')}</span><span><strong>{r.name} {r.hasPassword&&<Lock size={14} aria-label="Có mật khẩu"/>}</strong><small>{r.memberCount}/{r.capacity} người</small></span><b>{r.memberCount>=r.capacity?'FULL':'Vào phòng →'}</b></button>)}{rooms.length===0&&<div className="plaza-v7-empty"><DoorOpen/><h2>Cuộc gặp đầu tiên chờ bạn</h2><p>Tạo phòng để mời bạn bè vào Plaza.</p></div>}</div></section>:<section className="plaza-v7-placeholder"><img src={portraits(profile.character)} alt="Nhân vật mặc định"/><h1>{title[view]}</h1><p>{view==='wardrobe'?'Nhân vật mặc định của bạn. Danh sách vật phẩm sẽ hiển thị khi hệ thống tủ đồ được kết nối.':'Siêu thị đang được chuẩn bị. Vật phẩm và danh hiệu sẽ có mặt trong bản cập nhật tiếp theo.'}</p><button onClick={()=>setView('hub')}>Về sảnh</button></section>}</>}
 {modal&&<div className="plaza-v7-modal"><form onSubmit={async e=>{e.preventDefault();const ok=modal.create?await onCreate(locked?password:''):await onJoin(modal.roomId,password);if(ok){setModal(null);setPassword('');}}}><h2>{modal.create?'Tạo phòng mới':modal.name}</h2>{modal.create&&<label><input type="checkbox" checked={locked} onChange={e=>setLocked(e.target.checked)}/> Đặt mật khẩu</label>}{(!modal.create||locked)&&<label>Mật khẩu<input autoFocus type="password" value={password} onChange={e=>setPassword(e.target.value)} minLength={4} maxLength={64} required/></label>}<p>Tối đa 30 người mỗi phòng.</p><button disabled={!connected||busy}> {modal.create?'Tạo phòng':'Vào phòng'} </button><button type="button" disabled={busy} onClick={()=>setModal(null)}>Hủy</button></form></div>}
 </div>;
}
